### ISSUE TITLE
Class Fourier  may be err when  caculate dq

### ISSUE THREAD

**Issue by dbdxnuliba** [WPI-AIM/dvrk_dynamics_identification#1]
when I run this script ,we got the result of excited_trajectory  about q,dq,ddq.
but the curve of dq  didn't correspd to the curve of q's diff,
I have tested many time , the result of the curve dq is wrong.
The definition of Class Fourier  in fourier.py  is wrong.

so once the dq is wrong ,the cond(H)will wrong ,so the x_result of ols is wrong.
I hope you can pay attention to the issue

**Comment by dbdxnuliba** [comment]
you can change the fourier.py  ffile accorrding 
to the following cpp

    double position = traj->q0;
    double velocity = 0;
    double acceleration = 0;

    for(int i = 0; i < traj->a.size(); i++)
    {
        double phase = traj->w_f*(i+1)*t;
        double s = sin(phase);
        double c = cos(phase);

        position += traj->a[i]/(traj->w_f*(i+1))*s - traj->b[i]/(traj->w_f*(i+1))*c;
        velocity += traj->a[i]*c + traj->b[i]*s;
        acceleration += -traj->a[i]*(traj->w_f*(i+1))*s + traj->b[i]*(traj->w_f*(i+1))*c;
    }

**Comment by wangyanhit** [comment]
hey, thanks for the question. I have never tested if the position, velocity, and acceleration are corresponding to each other. But here I got one example from my previous experiment for the MTM
![image](https://user-images.githubusercontent.com/24853292/77741476-eaaaa280-704f-11ea-99d8-50daaf64b239.png)
I drew 4 time lines. At the first and second times, the position reaches a peak, and at the same time the velocity is around 0; Similarly, the others also make sense to me.  
And from the definition of q, dq, and ddq, I don't see any problem. Can you double-check it for me?
![image](https://user-images.githubusercontent.com/24853292/77742311-432e6f80-7051-11ea-9411-71ca03561153.png)

**Comment by wangyanhit** [comment]
And even though the trajectory generation is not correct, it won't affect the identified parameters. It will only affect the quality of the generated trajectory.

**Comment by dbdxnuliba** [comment]
you can test 
a demo
rbtdef = sympybotics.RobotDef("selfRobot_2dof",
            [(0, 0, 0.3055, "q"),
             ("-pi/2", 0, 0.1925, "q")],
            dh_convention="mdh")
#rbtdef.frictionmodel = {}
rbtdef.frictionmodel = {'Coulomb','viscous'}


from trajectory_optimization import TrajOptimizer
from trajectory_optimization import TrajPlotter
from numpy import deg2rad



base_freq = 0.05
fourier_order = 6

joint_constraints = []
cartesian_constraints = []


joint_constraints = [(1, deg2rad(-180), deg2rad(180), deg2rad(-120), deg2rad(120)),
                     (2, deg2rad(-170), deg2rad(-10), deg2rad(-120), deg2rad(120))]

    
traj_optimizer = TrajOptimizer(rbt, fourier_order, base_freq,
                               joint_constraints=joint_constraints,
                               cartesian_constraints = cartesian_constraints)
                                                                                                 
                                                                                                                     
traj_optimizer.optimize()


then it produce q,dq,ddq curve
and trajectory  csv file containing only q 
when you caculate dq_diff  by ( q_next -q_now)/0.02 in the csv file
you can get dq_diff 
then when you plot dq_diff curve  
you will find the dq_diff curve shape  caculated in csv file  will didn't agree with the script plot dq curve 

I can send you the detailed content if you can show me your email.

**Comment by dbdxnuliba** [comment]
![1](https://user-images.githubusercontent.com/13350158/78019288-0086d300-7382-11ea-9e03-42cd2280e8b9.png)
this is script result q, dq ,ddq curve

**Comment by dbdxnuliba** [comment]
![2](https://user-images.githubusercontent.com/13350158/78019734-bd792f80-7382-11ea-9877-4cfca713b96f.png)
this is  q and dq(caculated by q's diff)

**Comment by dbdxnuliba** [comment]
we can find q curve is the same, but dq_curve caculated by diff method is not very same with dq curve the script caculated

**Comment by wangyanhit** [comment]
yes, please send the things to me through wangyanhiter@gmail.com. thanks

**Comment by wangyanhit** [comment]
And where is the csv file from? And can you plot those two velocities in the same figure? that will make it easier to see.

**Comment by dbdxnuliba** [comment]
![2](https://user-images.githubusercontent.com/13350158/78095893-c1e92b00-740a-11ea-9033-bc8c69b7599c.PNG)
this is the q curve and dq curve (dq_curve caculated by diff method)

**Comment by dbdxnuliba** [comment]
ok ,I see ,but the  Hb_mtrix  formula is so complex ,
so  it's not coveninet to produce Hb_code to C++ code .
do you have convient method 

![3](https://user-images.githubusercontent.com/13350158/78115527-8021aa00-7435-11ea-98b4-be867736f253.png)

**Comment by wangyanhit** [comment]
yes, that matrix is super complex. if you want to use it on a robot with less than 4 DoFs I guess it's fine. But if you want to use it on a robot with higher DoFs I highly recommend you use the recursive Newton-Euler method, which is more computationally efficient.

**Comment by wangyanhit** [comment]
Can you push your code with the two-link arm to your GitHub such that I can check the trajectory problem using your simple case?

**Comment by dbdxnuliba** [comment]
ok ,I use https://github.com/kiwiwan/ur10_dyn_ident script
to create  2dof robot , then I found the problem

**Comment by dbdxnuliba** [comment]
I has sent you an email 
you can try test.
thanks a lot
![image](https://user-images.githubusercontent.com/13350158/78862121-2dfe0b80-7a69-11ea-8a82-b8cbbeea959e.png)

**Comment by wangyanhit** [comment]
I find the problem. My code is correct. The problem is that when you use the difference between the next q and the current q to calculate the velocity there will be a phase lag by the time interval. Since in my original program I only sampled 12 points in one period for the highest-frequency component it becomes very prominent when you do this. I select a number 12 becuase when it is larger the H matrix will become larger and it will cost more time for the optimization. You can try to make the two curves closer by increasing the sample_point in traj_optimizer.py
![image](https://user-images.githubusercontent.com/24853292/78866937-4a208f00-7a0e-11ea-8058-9f2d5152aa40.png)
this is the result I get when sample_point is 50. They are very close to each other now.

**Comment by wangyanhit** [comment]
[main_two_link_robot.ipynb.zip](https://github.com/WPI-AIM/dvrk_dynamics_identification/files/4454556/main_two_link_robot.ipynb.zip)
this is the file for a random 2-link robot I created.

**Comment by wangyanhit** [comment]
If you can do well in the dynamic model identification of UR10 I can put a link of your result in this repo such that more people may use it for different robots in the future.

**Comment by dbdxnuliba** [comment]
thanks ,the  velocity at start time is not close to zero ,this may casue pound to arm ,why don't you constrain the vstart and vend  close to zero

**Comment by wangyanhit** [comment]
![image](https://user-images.githubusercontent.com/24853292/78959739-7b888000-7b1e-11ea-9c33-c174e82260e8.png)
I actually made the starting velocity zero here. you can modify it to make the ending velocity zero too.

**Comment by wangyanhit** [comment]
My robot is not very stiff so that it can bear some small impact. But for a general industrial arm with a large reduction ratio, I agree it is a good idea to make the velocity zero at the beginning and the end.

**Comment by dbdxnuliba** [comment]
![image](https://user-images.githubusercontent.com/13350158/78968447-3290f580-7b37-11ea-90bd-8f8465f63047.png)
your velocity result show some joint starting velocity is not zero

**Comment by wangyanhit** [comment]
I will do that when I run the robot. It's not in the ipynb file.

**Comment by dbdxnuliba** [comment]
ok ,and I find the  result q_curve is different from each other between two times running the script
this is the first time's  q_curve 
![image](https://user-images.githubusercontent.com/13350158/78969684-1e9ac300-7b3a-11ea-8991-71da3f5c9d37.png)
this is the second time's q_curve
![image](https://user-images.githubusercontent.com/13350158/78969800-72a5a780-7b3a-11ea-954f-35a2f4348831.png)

**Comment by dbdxnuliba** [comment]
so the result is not same each time run the script ,isn't it?

**Comment by wangyanhit** [comment]
> so the result is not same each time run the script ,isn't it?

you are right. it's a nonlinear optimization, which doesn't ensure global optimal solution and relies on the initial guess. I think I used random initial guess.

**Comment by dbdxnuliba** [comment]
ok ,thanks a lot
